services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5673:5672"
      - "15673:15672"

  consumer:
    image: noctrunal/event-consumer:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
